#!/bin/sh

if ! [ $(id -u) = 0 ]; then
	echo 'This script must be run as root!'
	exit 1
fi

EXPECTED_SIGNATURE=$(wget https://composer.github.io/installer.sig -O - -q)
php -r "copy('https://getcomposer.org/installer', '/tmp/composer-setup.php');"
ACTUAL_SIGNATURE=$(php -r "echo hash_file('SHA384', '/tmp/composer-setup.php');")

if [ "$EXPECTED_SIGNATURE" = "$ACTUAL_SIGNATURE" ]
then
	php /tmp/composer-setup.php --install-dir=/usr/local/bin/ --filename=composer
	RESULT=$?
	rm /tmp/composer-setup.php
	sudo -u gituser -H composer global require nategood/httpful
	exit $RESULT
else
	>&2 echo 'ERROR: Invalid installer signature'
	rm /tmp/composer-setup.php
	exit 1
fi